- name: Change root password for all machines in scope
  hosts: all
  become: true
  gather_facts: false

   
  tasks:
  
    - name: Change user password   
      user:
        name: root
        password: "{{new_root_password_encrypted | password_hash }}"
