---
- name: Update all packages on Linux systems
  hosts: all
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update package list
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
